version: "3.9"

services:
  backend:
    build: ./backend
    container_name: timetable_backend
    ports:
      - "8004:8000"
    volumes:
      - ./backend:/app
      - ./backend/timetable.db:/app/timetable.db
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - timetable_network

  frontend:
    build: ./frontend
    container_name: timetable_frontend
    ports:
      - "5177:5173"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - timetable_network


networks:
  timetable_network:
    driver: bridge
